---
deployment:
  tasks:
    - export DEPLOYPATH=/home/myerstown/dev.myerstown.rosewoodhosting.us.com/myerstown
    - /usr/local/bin/composer install
    - /usr/bin/rsync -a --delete --exclude=".git" --exclude=".cpanel.yml" --exclude="web/sites/default/*.php" --exclude="web/sites/default/files" /home/myerstown/repositories/myerstownsheds/ $DEPLOYPATH
    - find /home/myerstown/dev.myerstown.rosewoodhosting.us.com/myerstown -type d -exec chmod 755 '{}' ';'
    - $DEPLOYPATH/vendor/bin/drush --root=$DEPLOYPATH/web --uri=dev.myerstown.rosewoodhosting.us.com cr