---
deployment:
  tasks:
    - export DEVPATH=/home/myerstown/dev.myerstown.rosewoodhosting.us.com/myerstown
    - export PRODPATH=/home/myerstown/public_html/myerstown
    - /usr/local/bin/composer install
    - /usr/bin/rsync -a --delete --exclude=".git" --exclude=".cpanel.yml" --exclude="web/sites/default/*.php" --exclude="web/sites/default/files" /home/myerstown/repositories/myerstownsheds/ $DEVPATH
    - find $DEVPATH -type d -exec chmod 755 '{}' ';'
