---
deployment:
  tasks:
    - export DEPLOYPATH=/home/myerstown/public_html/myerstown
    - /usr/local/bin/composer install
    - /usr/bin/rsync -a --delete --exclude=".git" --exclude=".cpanel.yml" --exclude="web/sites/default/*" /home/myerstown/repositories/myerstownsheds/ $DEPLOYPATH
    - find /home/myerstown/public_html/myerstown -type d -exec chmod 755 '{}' ';'